import"./assets/styles-CCJQcokt.js";import{a as f,i as C}from"./assets/vendor-u1GiHFh7.js";const w="https://dummyjson.com/",h={CATEGORIES:"/products/category-list",PRODUCTS:"/products",SEARCH:"/products/search",CATEGORY:"/products/category/"},s=12;f.defaults.baseURL=w;async function M(){const{data:t}=await f.get(h.CATEGORIES);return t}async function y(t=1){const e=(t-1)*s,{data:r}=await f.get(`${h.PRODUCTS}?limit=${s}&skip=${e}`);return r}async function b(t,e=1){if(!t||t.trim()==="")return{products:[],total:0,skip:0,limit:s};const r=(e-1)*s,c=encodeURIComponent(t);try{const{data:a}=await f.get(`${h.SEARCH}?q=${c}&limit=${s}&skip=${r}`);return a}catch(a){throw console.error(a),a}}const o={categoriesList:document.querySelector(".categories"),productsList:document.querySelector(".products"),loadMoreButton:document.querySelector(".load-more-btn"),searchForm:document.querySelector(".search-form"),blockNotFound:document.querySelector(".not-found"),clearInputBtn:document.querySelector(".search-form__btn-clear")};function S(t){const r=["All",...t].map(a=>`<li class="categories__item">
   <button class="categories__btn" type="button">${a}</button>
 </li>`).join("");o.categoriesList.innerHTML=r,document.querySelector(".categories__btn").classList.add("categories__btn--active")}function p(t){const e=t.map(({id:r,images:c,title:a,brand:B,category:k,price:E})=>`<li class="products__item" data-id="${r}">
    <img class="products__image" src="${c[0]}" alt="${a}"/>
    <p class="products__title">${a}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand: ${B||"Unknown"}</span></p>
    <p class="products__category">Category: ${k}</p>
    <p class="products__price">Price: ${E}</p>
 </li>`).join("");o.productsList.insertAdjacentHTML("beforeend",e)}function g(){o.productsList.innerHTML=""}function m(){o.loadMoreButton.classList.remove("is-hidden")}function l(){o.loadMoreButton.classList.add("is-hidden")}function v(){o.blockNotFound.classList.add("not-found--visible")}function L(){o.blockNotFound.classList.remove("not-found--visible")}function _(){o.clearInputBtn.classList.add("is-hidden")}function $(){o.clearInputBtn.classList.remove("is-hidden")}let n=1,i,d=!1,u="";async function I(){const t=await M();S(t),d=!1,u="",n=1;const{products:e,total:r}=await y();if(i=Math.ceil(r/s),n<=i)p(e),m();else{l();return}}async function P(){n+=1;let t,e;if(d&&u?{products:t,total:e}=await b(u,n):{products:t,total:e}=await y(n),i=Math.ceil(e/s),n<=i)p(t),m();else{C.warning({title:"❌",titleColor:"#fafafb",message:"You reached end of the catalogue",messageColor:"#fafafb",backgroundColor:"#ef4040",position:"bottomRight"}),l();return}}function R(t){const e=t.target.value;!e||e.length===0?_():$()}async function T(t){t.preventDefault();const r=new FormData(t.target).get("searchValue").trim();if(!r){C.error({title:"❌",titleColor:"#fafafb",message:"Enter the search query",messageColor:"#fafafb",backgroundColor:"#ef4040",position:"topRight"});return}g(),n=1,d=!0,u=r;const{products:c,total:a}=await b(r,n);if(i=Math.ceil(a/s),!c||c.length===0){d=!1,u="",v(),g(),l();return}L(),p(c),n<i?m():l()}async function A(){o.searchForm.elements.searchValue.value="",_(),g(),L(),d=!1,u="",n=1;try{const{products:t,total:e}=await y();if(i=Math.ceil(e/s),n<=i)p(t),m();else{l();return}}catch(t){throw console.error(t),t}}async function F(t){t.target.nodeName==="BUTTON"&&(t.target.textContent,n=1)}document.addEventListener("DOMContentLoaded",I);o.categoriesList.addEventListener("click",F);o.loadMoreButton.addEventListener("click",P);o.searchForm.addEventListener("submit",T);o.searchForm.addEventListener("input",R);o.clearInputBtn.addEventListener("click",A);
//# sourceMappingURL=index.js.map
