import"./assets/styles-CCJQcokt.js";import{a as f,i as C}from"./assets/vendor-u1GiHFh7.js";const S="https://dummyjson.com/",_={CATEGORIES:"/products/category-list",PRODUCTS:"/products",SEARCH:"/products/search",CATEGORY:"/products/category/"},r=12;f.defaults.baseURL=S;async function P(){const{data:t}=await f.get(_.CATEGORIES);return t}async function h(t=1){const e=(t-1)*r,{data:o}=await f.get(`${_.PRODUCTS}?limit=${r}&skip=${e}`);return o}async function b(t,e=1){if(!t||t.trim()==="")return{products:[],total:0,skip:0,limit:r};const o=(e-1)*r,n=encodeURIComponent(t);try{const{data:c}=await f.get(`${_.SEARCH}?q=${n}&limit=${r}&skip=${o}`);return c}catch(c){throw console.error(c),c}}async function $(t,e=1){const o=(e-1)*r,{data:n}=await f.get(`${_.CATEGORY}${t}?limit=${r}&skip=${o}`);return n}async function I(t){return(await f.get(`${_.PRODUCTS}/${t}`)).data}const a={categoriesList:document.querySelector(".categories"),productsList:document.querySelector(".products"),loadMoreButton:document.querySelector(".load-more-btn"),searchForm:document.querySelector(".search-form"),blockNotFound:document.querySelector(".not-found"),clearInputBtn:document.querySelector(".search-form__btn-clear"),modal:document.querySelector(".modal"),modalContent:document.querySelector(".modal-product"),modalCloseBtn:document.querySelector(".modal__close-btn")};function R(t){const o=["All",...t].map(c=>`<li class="categories__item">
   <button class="categories__btn" type="button">${c}</button>
 </li>`).join("");a.categoriesList.innerHTML=o,document.querySelector(".categories__btn").classList.add("categories__btn--active")}function y(t){const e=t.map(({id:o,images:n,title:c,brand:w,category:E,price:M})=>`<li class="products__item" data-id="${o}">
    <img class="products__image" src="${n[0]}" alt="${c}"/>
    <p class="products__title">${c}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand: ${w||"Unknown"}</span></p>
    <p class="products__category">Category: ${E}</p>
    <p class="products__price">Price: ${M}</p>
 </li>`).join("");a.productsList.insertAdjacentHTML("beforeend",e)}function g(){a.productsList.innerHTML=""}function p(){a.loadMoreButton.classList.remove("is-hidden")}function l(){a.loadMoreButton.classList.add("is-hidden")}function v(){a.blockNotFound.classList.add("not-found--visible")}function L(){a.blockNotFound.classList.remove("not-found--visible")}function B(){a.clearInputBtn.classList.add("is-hidden")}function T(){a.clearInputBtn.classList.remove("is-hidden")}function A(){document.querySelectorAll(".categories__btn--active").forEach(e=>{e.classList.remove("categories__btn--active")})}function q(){a.modal.classList.add("modal--is-open")}function F(){a.modal.classList.remove("modal--is-open")}function N(t){const e=`<img class="modal-product__img" src="${t.images[0]}" alt="${t.title}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${t.title}</p>
        <ul class="modal-product__tags">
        <li class="modal-product__tag">${t.tags[0]||""} </li>
         <li class="modal-product__tag">${t.tags[1]||""} </li>
        </ul>
        <p class="modal-product__description">${t.description}</p>
        <p class="modal-product__shipping-information">Shipping: ${t.shippingInformation}</p>
        <p class="modal-product__return-policy">Return Policy: ${t.returnPolicy}</p>
        <p class="modal-product__price">Price: ${t.price}</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div>`;a.modalContent.innerHTML=e}let s=1,i,m=!1,u="",d="";async function k(){const t=await P();R(t),m=!1,u="",d="ALL",s=1;const{products:e,total:o}=await h();if(i=Math.ceil(o/r),s<=i)y(e),p();else{l();return}}async function O(){s+=1;let t,e;if(m&&u?{products:t,total:e}=await b(u,s):d&&d!=="ALL"?{products:t,total:e}=await $(d,s):{products:t,total:e}=await h(s),i=Math.ceil(e/r),s<=i)y(t),p();else{C.warning({title:"❌",titleColor:"#fafafb",message:"You reached end of the catalogue",messageColor:"#fafafb",backgroundColor:"#ef4040",position:"bottomRight"}),l();return}}function D(t){const e=t.target.value;!e||e.length===0?B():T()}async function U(t){t.preventDefault();const o=new FormData(t.target).get("searchValue").trim();if(!o){C.error({title:"❌",titleColor:"#fafafb",message:"Enter the search query",messageColor:"#fafafb",backgroundColor:"#ef4040",position:"topRight"});return}g(),s=1,d="all",m=!0,u=o;const{products:n,total:c}=await b(o,s);if(i=Math.ceil(c/r),!n||n.length===0){m=!1,u="",v(),g(),l();return}L(),y(n),s<i?p():l()}async function H(){a.searchForm.elements.searchValue.value="",B(),g(),L(),m=!1,u="",s=1;try{const{products:t,total:e}=await h();if(i=Math.ceil(e/r),s<=i)y(t),p();else{l();return}}catch(t){throw console.error(t),t}}async function G(t){if(t.target.nodeName!=="BUTTON")return;A();const e=t.target.textContent.toLowerCase();if(d=e,s=1,m=!1,u="",e==="all")t.target.classList.add("categories__btn--active"),g(),l(),await k(),p();else{t.target.classList.add("categories__btn--active"),g(),l();try{const{total:o,products:n}=await $(d,s);if(!n||n.length===0?v():L(),i=Math.ceil(o/r),y(n),s+=1,s<=i)p();else{l();return}}catch(o){throw console.error(o),o}}}async function j(t){if(t.target.nodeName!=="LI")return;const e=t.target.dataset.id,o=await I(e);N(o),q()}document.addEventListener("DOMContentLoaded",k);a.categoriesList.addEventListener("click",G);a.loadMoreButton.addEventListener("click",O);a.searchForm.addEventListener("submit",U);a.searchForm.addEventListener("input",D);a.clearInputBtn.addEventListener("click",H);a.productsList.addEventListener("click",j);a.modalCloseBtn.addEventListener("click",F);
//# sourceMappingURL=index.js.map
